development: &default
  adapter: postgresql
  database: resque_vs_sidekiq_development
  pool: 30
  timeout: 5000
  min_messages: warning

test: &test
  <<: *default
  database: resque_vs_sidekiq_test

production: &production
  <<: *default
  database: resque_vs_sidekiq_production
